[package]
name = "cone"
version = "0.1.0"
edition = "2021"

[dependencies]
ssh2 = "0.9"
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
shellexpand = "3.1.0"
chrono = "0.4"
openssl = { version = "0.9", features = ["vendored"] }
